### ISSUE TITLE
Todo tasks

### ISSUE THREAD

**Issue by tiaguinhor** [tiaguinhor/youtube-video-maker#1]
- [x] Especificar tarefas e escopos

---

- [x] **Orquestrador**
  - [x] Perguntar pelo termo de busca
  - [x] Perguntar pelo prefixo
  - [x] Iniciar robo de texto
  - [x] Iniciar robo de imagens
  - [x] Iniciar robo de video
  - [x] Iniciar robo do youtube

---

- [x] **Robo de Texto**
  - [x] Estrutura de dados
  - [x] Pegar conteudo do wikipedia
  - [x] Limpar o conteudo
  - [x] Quebrar em sentencas
  - [x] Pegar a interpretacao do Watson
  - [x] Adicionar tags
  - [x] Salvar estrutura de dados

---

- [x] **Robo de Imagens**
  - [x] Carregar a estrutura de dados
  - [x] Buscar imagens no google
  - [x] Baixar imagens
  - [x] Salvar estrutura de dados

---

- [x] **Robo de Video**
  - [x] Preparar/redimensionar imagens
  - [x] Criar sentencas com imagens
  - [x] Criar thumbnail para o video
  - [x] Renderizar o video com after effects

---

- [x] **Robo do Youtube**
  - [x] Autenticar com Oauth
  - [x] Upload video
  - [x] Upload thumbnail
